# -*- coding: utf-8 -*-
"""9. 산점도.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OEemL_lZqSkMygWdD9_dHlKMGD5DwGH9
"""

from sklearn.datasets import load_diabetes

diabetes = load_diabetes()
print(diabetes.data.shape, diabetes.target.shape)
# 행은 샘플 열은 샘플의 특성

print(diabetes.data[0:3])

print(diabetes.target[:3])

# 당뇨병 환자 산점도
import matplotlib.pyplot as plt
plt.scatter(diabetes.data[:,2], diabetes.target)
plt.xlabel('X')
plt.ylabel('Y')
plt.show()

x = diabetes.data[:,2]
y = diabetes.target

